base:
  project_name: credit-card-fraud-mlops
  random_state: 42

data_split:
  test_size: 0.3
  stratify: true

smote:
  random_state: 42

model:
  name: xgboost
  objective: binary:logistic
  eval_metric: logloss
  n_estimators: 500
  max_depth: 6
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
